nelmio_api_doc:
    documentation:
        info:
            title: Flat101 Product API
            description: API REST para gesti√≥n de productos
            version: 1.0.0
        servers:
            - url: http://localhost
              description: Development server
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc)
