services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flat101_php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - flat101_network
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-debug,coverage}
      - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-host.docker.internal}
      - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT:-9003}

  nginx:
    image: nginx:alpine
    container_name: flat101_nginx
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-80}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - flat101_network
    depends_on:
      - php

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  flat101_network:
    driver: bridge


volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
