services:
  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: app_runtime
    container_name: product_api_php
    restart: unless-stopped
    volumes:
      - ../:/var/www/html:rw,delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/app.ini:ro
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-apiDDDTest1234}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}&charset=utf8
      XDEBUG_MODE: ${XDEBUG_MODE:-debug,coverage}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: product_api_nginx
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8000}:80"
    volumes:
      - ../:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app_network

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: product_api_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apiDDDTest1234}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-app}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database_data:
