controllers:
    resource:
#        path: ../src/Presentation/Controller/
#        namespace: App\Presentation\Controller
         path: ../src/Controller/
         namespace: App\Controller
    type: attribute
